#! /usr/bin/env bash

# Create our VPC
aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region eu-west-2 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]' \
--query Vpc[0].VpcId

# Create an IGW

# Attach an IGW

# Create 