#! /usr/bin/env bash
echo "== create bucket"


# Check if the first argument is provided
if [ -z "$1" ]; then
  echo "There needs be a bucket name."
  exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region eu-west-2 \
--create-bucket-configuration="LocationConstraint=eu-west-2" \
--query Location \
--output text