#! /usr/bin/env bash
echo "== sync"

# Exit immediately if any command returns a non-zero status.
set -e

# Check if the first argument is provided
if [ -z "$1" ]; then
  echo "There needs be a bucket name."
  exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
  echo "There needs be a bucket name."
  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store thes files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove the folder if it already exists
rm -r $OUTPUT_DIR
mkdir -p $OUTPUT_DIR

# Generate a random number between 5 and 10
NUM_FILES=$((RANDOM % 6 + 5))

echo "Creating $NUM_FILES random files..."

for ((i=1; i<=$NUM_FILES; i++)); do
  # Generate a random filename using uuid or random string
  FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"

  # Generate random data and write it to the file
  dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
  echo "Created file: $filename"
done

tree $OUTPUT_DIR
aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files